name: ecom-datalake-exten
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas>=2.1,<3
  - pyarrow>=14,<16
  - click>=8.1,<9
  - python-dateutil>=2.8,<3
  - tqdm>=4.66,<5
  - pendulum>=3,<4
  - pytest>=8,<9
  - pip:
      - google-cloud-storage>=2.12,<3
      - black>=24.4,<25
      - ruff>=0.5,<0.6
      - build>=1.2,<2
