name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          pip install 'git+https://github.com/G-Schumacher44/ecom_sales_data_generator.git#egg=ecom_sales_data_generator'

      - name: Lint with ruff
        run: ruff check src tests

      - name: Check formatting with black
        run: black --check src tests

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build
